### ISSUE TITLE
Game Title

### ISSUE THREAD

**Issue by Ohrwerk** [TakoNekko/SteamGridManager#1]
Unfortunately, I do not see the title of any game.
Is this tool still active?

**Comment by TakoNekko** [comment]
Sorry for the late reply! I don't think anybody uses my app, so not really ahah... But thanks for the report, I'll take a look at it now.

**Comment by TakoNekko** [comment]
Importing steam apps works again, beware that it can take a minute to load if your library is really huge.

**Comment by Ohrwerk** [comment]
Edit:

13. August 2023
I looked at the whole thing again tonight.
In folder ...Steam\...\config\grid were a high number of additional header graphics with a very long numeric file name (11680620958342709248, 4803104910344192, ...).
I removed these files and now the list of games is displayed correctly with all graphics except for the titles of the games.

Game titles are not displayed for non-Steam games (shortcuts). 
In the properties (F4) the game title is displayed correctly under AppName.

For Steam games the titles are displayed now. Great, one step further.


Your tool is excellent by the way, especially now that you can't use custom artwork with the new horrible Steam client. Doesn't work anymore, unfortunately.
Also Daniel-Griffiths / vapour is no longer under development, i would much rather use an alternative client than this impossible thing from Steam.



12. August 2023
Thank you.
First Test:
The game titles of Steam games are now displayed.
I currently have 628 items in the list, of which 588 are links from "non-Steam" games.
With these shortcuts, a lot of Library, Hero and Logo graphics are not displayed. Header graphics are displayed correctly at first sight for all shortcuts.
Game titles are not shown for these shortcuts, but they are shown under Properties, but only for games where not only the header graphic is shown. If only the header graphic is displayed, I also have no access to the properties to show me ,ore informations.

**Comment by Ohrwerk** [comment]
I have uploaded the file with the shortcuts, maybe it helps.
https://drive.google.com/file/d/1L7k5ze6N9F1X6xA91Kh1GSA3IQW1Uxar/view

**Comment by TakoNekko** [comment]
Thanks for the new report, I'll take a look at it now.

**Comment by TakoNekko** [comment]
Looking at your `shortcuts.vdf` file, the `appname` field has been renamed `AppName`...

**Comment by TakoNekko** [comment]
Shortcut titles should be displayed correctly now.

**Comment by TakoNekko** [comment]
Concerning the shortcuts with long digits... I had a couple of those too, but I can't remember if I found the reason and a solution for it... These application ID's can't be saved to `shortcuts.vdf` since those numbers are 64-bit unsigned integers and the VDF file format only supports writing 32-bit integers. You could tell me the app id (e.g., 11680620958342709248) and name of the game and see if I can find an entry for it in your `shortcuts.vdf` file. Otherwise, if you don't have many of those, it might be best to just recreate those shortcuts entirely.

**Comment by Ohrwerk** [comment]
After I did the cleanup with the header files, there were 491 items left.
Of these, all Steam games are displayed correctly and also a large part of the shortcuts.

For 130 items, no title is still displayed.
Here are a few examples:
APPID                   TITLE                       Collection
2785897818         Pine                         [01] EPICGAMES.COM (Duplicate of 2792971839)
2719398339         Dreamscapes          ???   (Shortcut not exist in Steam Client)

i looked at some, all are probably duplicates of existing and correctly displayed games or of deleted shortcuts. So I can delete these files, which I have already done for a few (duplicates) to try.
Let's see, either I ignore the entries or I delete the graphics of the 120+ entries.
Thank you very much for your support.

**Comment by Ohrwerk** [comment]
I think it is also necessary to have a look at "View/List/Custom Columns", AppName and EXE do not work either.
That's all I have tested there at the moment.
Also with the icons it has probably become more problematic through updates from Steam.
I have not managed to change the icon of a Steam game, the game properties of Steam do not or no longer offer this.
Also manually I could not force a swap of the icon via a file 6040_icon.ico (AppID_icon.ICO/PNG/JPG) in the folder
...\Steam\userdata\*********\config\grid.
For non-Steam games the icon is probably selected in the properties and the path is probably stored in the Shortcuts.vdf.
I don't know, I haven't found a tool to de/encode the Shortcuts file.

**Comment by TakoNekko** [comment]
Those appID's do not exist in your `shortcuts.vdf` file, perhaps those asset files could be leftovers that didn't get clean up correctly by Steam when you deleted or created similar shortcuts.

**Comment by TakoNekko** [comment]
The Custom Columns menu is only partially implemented and doesn't support conditional paths, which is an undocumented feature... You can do it manually by opening the options dialog, and under `Interface`/`List`/`Columns`/`Custom VDF Columns`, add two new lines, `appname||AppName` and `exe||Exe`, then press `OK`.

**Comment by TakoNekko** [comment]
You can replace shortcut icons by making a backup of your `shortcuts.vdf` (the app does that automatically, but just to be safe), then dropping a file on the icon slot then right clicking on the preview image then choosing `Set as Custom Icon`, then once you changed all your icons, click on `Tools`/`Database`/`Save Shortcuts`.

However, do note that Steam ignore changes to `shortcuts.vdf` while Steam is running and will then overwrite the file when it closes. So make sure you change the icons and save the file only when Steam is not running.

Also, you probably don't want to use the menu `Tools`/`Shortcut Icons`/`...`, this is only if you want to batch extract/copy every shortcut icon and place them all in the same directory. It's probably more performant than letting Steam scan every executable file all the time, but it's also probably too high maintenance if you have many shortcuts.

As for steam app icons, I can't remember at all if it was possible to change them, but if I didn't disable the icon slot for them, then I guess it must have worked...?

**Comment by Ohrwerk** [comment]
Thank you very much for your support.
I actually did not click on "Set as Custom Icon" in the menu.
Now it works and i also found a way to change the Icon of a Steam Game.

**Comment by TakoNekko** [comment]
I'm glad you got everything to work!
